document.writeln("<div class=\"qqbox\" id=\"divQQbox\">");
document.writeln("  <div class=\"qqlv\" id=\"meumid\" onmouseover=\"qqshow()\"><img src=\"http:\/\/www.socket.net.cn\/qq\/qq.gif\" \/><\/div>");
document.writeln("  <div class=\"qqkf\" style=\"display:none;\" id=\"contentid\" onmouseout=\"hideMsgBox(event)\">");
document.writeln("    ");
document.writeln("	<div class=\"qqkfbt\">在线服务<\/div>");
document.writeln("    <div>");
document.writeln("	<table  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" >");
document.writeln("		<tr>");

document.writeln("	  <td height=\"30\"><div class=\"qqkfbtaa\">");
document.writeln("	  <a href=\'tencent:\/\/message\/?uin=1114789216&Site=West369.Com&Menu=yes\' title=\'产品咨询\'><img src=\'http:\/\/wpa.qq.com\/pa?p=1:1114789216:4\' border=\'0\'><\/a> <\/div>");
document.writeln("	  <\/td>");
document.writeln("		<td>");
document.writeln("		<a href=\'tencent:\/\/message\/?uin=1114789216&Site=West369.Com&Menu=yes\' title=\'产品咨询\'>产品咨询<\/a> ");
document.writeln("		<\/td>		");
document.writeln("		<\/tr>");
document.writeln("		");
document.writeln("		<tr>");
document.writeln("	    <td height=\"30\"><div class=\"qqkfbtaa\">");
document.writeln("	  <a href=\'tencent:\/\/message\/?uin=513848293&Site=West369.Com&Menu=yes\' title=\'招商加盟\'><img src=\'http:\/\/wpa.qq.com\/pa?p=1:513848293:4\' border=\'0\'><\/a>  <\/div>");
document.writeln("	  <\/td>");
document.writeln("		<td>");
document.writeln("		<a href=\'tencent:\/\/message\/?uin=513848293&Site=West369.Com&Menu=yes\' title=\'招商加盟\'>招商加盟<\/a> ");
document.writeln("		<\/td>		");
document.writeln("		<\/tr>");
document.writeln("		");
document.writeln("		<tr>");
document.writeln("	    <td height=\"30\"><div class=\"qqkfbtaa\">");
document.writeln("	  <a href=\'tencent:\/\/message\/?uin=24257729&Site=West369.Com&Menu=yes\' title=\'技术支持\'><img src=\'http:\/\/wpa.qq.com\/pa?p=1:24257729:4\' border=\'0\'><\/a>  <\/div>");
document.writeln("	  <\/td>");
document.writeln("		<td>");
document.writeln("		<a href=\'tencent:\/\/message\/?uin=24257729&Site=West369.Com&Menu=yes\' title=\'技术支持\'>技术支持<\/a> ");
document.writeln("		<\/td>		");
document.writeln("		<\/tr>");
document.writeln("		");
document.writeln("		<tr>");
document.writeln("	    <td height=\"30\"><div class=\"qqkfbtaa\">");
document.writeln("	  <a href=\'tencent:\/\/message\/?uin=1404089546&Site=West369.Com&Menu=yes\' title=\'售后服务\'><img src=\'http:\/\/wpa.qq.com\/pa?p=1:1404089546:4\' border=\'0\'><\/a>  <\/div>");
document.writeln("	  <\/td>");
document.writeln("		<td>");
document.writeln("		<a href=\'tencent:\/\/message\/?uin=1404089546&Site=West369.Com&Menu=yes\' title=\'售后服务\'>售后服务<\/a> ");
document.writeln("		<\/td>		");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("");
document.writeln("    <\/div>");
document.writeln("    ");
document.writeln("  <\/div>");
document.writeln("<\/div>");
document.writeln("<script>");
document.writeln("");
document.writeln("var tips; ");
document.writeln("var theTop = 100;");
document.writeln("var old = theTop;");
document.writeln("function initFloatTips() ");
document.writeln("{ ");
document.writeln("	tips = document.getElementById(\'divQQbox\');");
document.writeln("	moveTips();");
document.writeln("}");
document.writeln("");
document.writeln("function moveTips()");
document.writeln("{");
document.writeln("	 	  var tt=50; ");
document.writeln("		  if (window.innerHeight) ");
document.writeln("		  {");
document.writeln("			  pos = window.pageYOffset  ");
document.writeln("		  }else if (document.documentElement && document.documentElement.scrollTop) {");
document.writeln("			 pos = document.documentElement.scrollTop  ");
document.writeln("		  }else if (document.body) {");
document.writeln("		    pos = document.body.scrollTop;  ");
document.writeln("		  }");
document.writeln("		  ");
document.writeln("		  pos=pos-tips.offsetTop+theTop; ");
document.writeln("		  pos=tips.offsetTop+pos\/10; ");
document.writeln("		  if (pos < theTop){");
document.writeln("			 pos = theTop;");
document.writeln("		  }");
document.writeln("		  if (pos != old) { ");
document.writeln("			 tips.style.top = pos+\"px\";");
document.writeln("			 tt=10;  \/\/alert(tips.style.top);  ");
document.writeln("		  }");
document.writeln("		  old = pos;");
document.writeln("		  setTimeout(moveTips,tt);");
document.writeln("}");
document.writeln("initFloatTips();");
document.writeln("");
document.writeln("	if(typeof(HTMLElement)!=\"undefined\")    \/\/给firefox定义contains()方法，ie下不起作用");
document.writeln("		{  ");
document.writeln("		  HTMLElement.prototype.contains=function (obj)  ");
document.writeln("		  {  ");
document.writeln("			  while(obj!=null&&typeof(obj.tagName)!=\"undefind\"){ \/\/通过循环对比来判断是不是obj的父元素");
document.writeln("	   　　 　if(obj==this) return true;  ");
document.writeln("	   　　　	　obj=obj.parentNode;");
document.writeln("	   　　	  }  ");
document.writeln("			  return false;  ");
document.writeln("		  }");
document.writeln("	}");
document.writeln("");
document.writeln("function qqshow()");
document.writeln("{");
document.writeln("	document.getElementById(\"meumid\").style.display=\"none\"");
document.writeln("	document.getElementById(\"contentid\").style.display=\"block\"");
document.writeln("}");
document.writeln("	function hideMsgBox(theEvent){");
document.writeln("	  if (theEvent){");
document.writeln("		var browser=navigator.userAgent;");
document.writeln("		if (browser.indexOf(\"Firefox\")>0){  \/\/如果是Firefox");
document.writeln("		    if (document.getElementById(\"contentid\").contains(theEvent.relatedTarget)) {  \/\/如果是子元素");
document.writeln("				return");
document.writeln("			}");
document.writeln("		}");
document.writeln("		if (browser.indexOf(\"MSIE\")>0 || browser.indexOf(\"Presto\")>=0){  \/\/如果是IE");
document.writeln("	        if (document.getElementById(\'contentid\').contains(event.toElement)) {  \/\/如果是子元素");
document.writeln("			    return;  \/\/结束函式");
document.writeln("		    }");
document.writeln("		}");
document.writeln("	  }");
document.writeln("	  document.getElementById(\"meumid\").style.display = \"block\";");
document.writeln("	  document.getElementById(\"contentid\").style.display = \"none\";");
document.writeln(" 	}");
document.writeln("<\/script> ");