#pragma once


#define MAKE_A_JQ(color,name)  ( (color) * 100 +(name))
#define GET_A_JQ_COLOR(a)  ( (a) / 100)
#define GET_A_JQ_NAME(a)  ( (a) % 100)

static int MakeAJq(int color,int name)
{
	return MAKE_A_JQ(color,name);
}

static int GetAJqCol(int jq)
{
	return GET_A_JQ_COLOR(jq) ;
}


static int GetAJqName(int jq)
{
	return GET_A_JQ_NAME(jq) ;
}
		
enum JQ_TYPE_COLOR
{
		JQ_TYPE_COLOR_NONE=-1,
		JQ_TYPE_COLOR_RED=1,
		JQ_TYPE_COLOR_BLUE=3,
		JQ_TYPE_COLOR_BLACK=0,
		JQ_TYPE_COLOR_GRAY=2

};

#define MAX_JQ_TYPE_COLOR   JQ_TYPE_COLOR_BLUE
#define MIN_JQ_TYPE_COLOR   JQ_TYPE_COLOR_BLACK


enum JQ_TYPE_NAME
{
		JQ_TYPE_NAME_NONE=-1,

		JQ_TYPE_NAME_SL = 12,	///< 司令
		JQ_TYPE_NAME_JZ= 11,	///< 军长
		JQ_TYPE_NAME_SZ = 10,	///< 师长
		JQ_TYPE_NAME_LIZ= 9,	///< 旅长
		JQ_TYPE_NAME_TZ = 8,	///< 团长
		JQ_TYPE_NAME_YZ = 7,	///< 营长
		JQ_TYPE_NAME_LIANZ=6,	///< 连长
		JQ_TYPE_NAME_PZ = 5,	///< 排长
		JQ_TYPE_NAME_GB = 4,	///< 工兵
		JQ_TYPE_NAME_DL = 3,	///< 地雷
		JQ_TYPE_NAME_JQ = 2,	///< 军旗
		JQ_TYPE_NAME_ZD = 1		///< 炸弹
		
};

#define MAX_JQ_TYPE_NAME   JQ_TYPE_NAME_SL
#define MIN_JQ_TYPE_NAME   JQ_TYPE_NAME_ZD



enum JQ_TYPE
{
			JQ_TYPE_NONE=MAKE_A_JQ(JQ_TYPE_COLOR_NONE,JQ_TYPE_NAME_NONE),

			JQ_TYPE_R_SL=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_SL),
			JQ_TYPE_R_JZ=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_JZ),
			JQ_TYPE_R_SZ=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_SZ),
			JQ_TYPE_R_LIZ=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_LIZ),
			JQ_TYPE_R_TZ=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_TZ),
			JQ_TYPE_R_YZ=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_YZ),
			JQ_TYPE_R_LIANZ=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_LIANZ),
			JQ_TYPE_R_PZ=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_PZ),
			JQ_TYPE_R_GB=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_GB),
			JQ_TYPE_R_DL=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_DL),
			JQ_TYPE_R_JQ=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_JQ),
			JQ_TYPE_R_ZD=MAKE_A_JQ(JQ_TYPE_COLOR_RED,JQ_TYPE_NAME_ZD),


            JQ_TYPE_B_SL=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_SL),
			JQ_TYPE_B_JZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_JZ),
			JQ_TYPE_B_SZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_SZ),
			JQ_TYPE_B_LIZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_LIZ),
			JQ_TYPE_B_TZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_TZ),
			JQ_TYPE_B_YZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_YZ),
			JQ_TYPE_B_LIANZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_LIANZ),
			JQ_TYPE_B_PZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_PZ),
			JQ_TYPE_B_GB=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_GB),
			JQ_TYPE_B_DL=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_DL),
			JQ_TYPE_B_JQ=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_JQ),
			JQ_TYPE_B_ZD=MAKE_A_JQ(JQ_TYPE_COLOR_BLUE,JQ_TYPE_NAME_ZD),

            JQ_TYPE_K_SL=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_SL),
			JQ_TYPE_K_JZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_JZ),
			JQ_TYPE_K_SZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_SZ),
			JQ_TYPE_K_LIZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_LIZ),
			JQ_TYPE_K_TZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_TZ),
			JQ_TYPE_K_YZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_YZ),
			JQ_TYPE_K_LIANZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_LIANZ),
			JQ_TYPE_K_PZ=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_PZ),
			JQ_TYPE_K_GB=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_GB),
			JQ_TYPE_K_DL=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_DL),
			JQ_TYPE_K_JQ=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_JQ),
			JQ_TYPE_K_ZD=MAKE_A_JQ(JQ_TYPE_COLOR_BLACK,JQ_TYPE_NAME_ZD),

			JQ_TYPE_G_SL=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_SL),
			JQ_TYPE_G_JZ=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_JZ),
			JQ_TYPE_G_SZ=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_SZ),
			JQ_TYPE_G_LIZ=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_LIZ),
			JQ_TYPE_G_TZ=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_TZ),
			JQ_TYPE_G_YZ=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_YZ),
			JQ_TYPE_G_LIANZ=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_LIANZ),
			JQ_TYPE_G_PZ=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_PZ),
			JQ_TYPE_G_GB=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_GB),
			JQ_TYPE_G_DL=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_DL),
			JQ_TYPE_G_JQ=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_JQ),
			JQ_TYPE_G_ZD=MAKE_A_JQ(JQ_TYPE_COLOR_GRAY,JQ_TYPE_NAME_ZD)
		
};




enum JQ_SHOW_SCAL
{
		JQ_SHOW_SCAL_HEIGHT=20,
		JQ_SHOW_SCAL_WEIGHT=20
};

/////end of pisa lib/////////////////////////////////////////////////////


#define JQ_H   20
#define JQ_W   20
















